# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("request_profiler", "0002_profilingrecord_http_referer")]

    operations = [
        migrations.AddField(
            model_name="profilingrecord",
            name="query_string",
            field=models.TextField(null=False, blank=True, verbose_name="Query string"),
        )
    ]
