# Generated by Django 4.1 on 2022-08-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_profiler", "0004_profilingrecord_query_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilingrecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ruleset",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
